export const GET_PAST_LAUNCHES_REQUEST = "GET_PAST_LAUNCHES_REQUEST"
export const GET_PAST_LAUNCHES_SUCCESS = "GET_PAST_LAUNCHES_SUCCESS"
export const GET_PAST_LAUNCHES_FAILURE = "GET_PAST_LAUNCHES_FAILURE"